@startuml
skinparam classAttributeIconSize 0
skinparam linetype ortho

class Dieta {
  +CARNIVORO
  +FOTOSSINTETICO
  +HERBIVORO
  +OMNIVORO
  --
}

class EntidadeCosmica {
  #__init__()
  #__repr__()
  +get_info()
}

class Planeta {
  #__init__()
  +get_info()
}

class EspecieAlien {
  #__init__()
  #_gerar_codigo_genetico()
  +e_perigoso()
}

class Inabitante {
  #__init__()
  +get_info()
}

class ZoologicoGalactico {
  #__init__()
  +adicionar_inabitante_a_jaula()
  +adicionar_jaula()
  +relatorio_geral()
}

class Jaula {
  #__init__()
  +adicionar_ocupante()
}

Enum <|-- Dieta
EntidadeCosmica <|-- Planeta
EntidadeCosmica <|-- Inabitante
@enduml