name: CI/CD - Geração de Artefatos e Versionamento

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz default-jre plantuml

    - name: Install Python dependencies (Gemini e PlantUML)
      run: |
        pip install --upgrade pip
        pip install google-generativeai plantuml

    - name: Instalar dependências do projeto
      run: |
        pip install -r requirements.txt

    - name: Gerar diagrama de classes
      run: python testes.py
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ github.run_id }}
        path: |
          artifacts/
          diagrama_classes.puml
          diagrama_classes.png

    - name: Commit e push dos diagramas gerados
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        git pull origin main

        git add diagrama_classes.*
        Git commit -m "Auto-generated: Update class diagrams [skip ci]" || echo "Nada para commitar"
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main
