name: Gerar Diagrama de Classes

on:
  push:
    branches:
      - main # Roda quando um push é feito para a branch 'main'
    paths:
      - '**.py' # Roda se qualquer arquivo Python for alterado
      - '.github/workflows/gerar_diagrama.yml' # Roda se este workflow for alterado

jobs:
  generate-diagram:
    runs-on: ubuntu-latest # O ambiente para executar a ação
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3 # Baixa seu código do GitHub

      - name: Instalar dependências (pylint para pyreverse, graphviz para renderizar)
        run: |
          python -m pip install --upgrade pip
          pip install pylint graphviz

      - name: Gerar diagrama de classes
        # pyreverse gera classes.png e packages.png
        # -p NomeDoProjeto é o nome do projeto no diagrama. Use o nome do seu repositório.
        # testes.py ou *.py se tiver mais arquivos python
        run: pyreverse -o png -p TestesClasses testes.py

      - name: Upload dos artefatos do diagrama
        uses: actions/upload-artifact@v4 # Este passo publica os arquivos gerados
        with:
          name: diagramas-de-classes # O nome do pacote de artefatos no GitHub
          path: |
            classes.png
            packages.png # Opcional, se você quiser também o diagrama de pacotes
          retention-days: 7 # Os artefatos ficarão disponíveis para download por 7 dias