name: Gerar Diagrama de Classes

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/gerar_diagrama.yml'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Graphviz (executável)
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Instalar dependências (pylint para pyreverse, biblioteca graphviz)
        run: |
          python -m pip install --upgrade pip
          pip install pylint graphviz

      - name: Gerar e Verificar Diagrama
        run: |
          set -x
          which pyreverse
          ls -lha .
          pyreverse -o dot -f ALL -p TestesClasses testes.py
          ls -lha .

      - name: Renomear arquivos gerados
        run: |
          mv classes_TestesClasses.dot classes.dot
          mv packages_TestesClasses.dot packages.dot

      - name: Upload dos artefatos do diagrama (em DOT)
        uses: actions/upload-artifact@v4
        with:
          name: diagramas-de-classes-dot
          path: |
            classes.dot
            packages.dot
          retention-days: 7
