- name: Gerar e Verificar Diagrama
        run: |
          which pyreverse
          echo "Conteúdo da pasta antes do pyreverse:"
          ls -lha .

          # --- MUDANÇA AQUI: Usa testes_simples.py ---
          pyreverse -o dot -p SimplesClasses testes_simples.py
          # ---------------------------------------------

          echo "Conteúdo da pasta depois do pyreverse:"
          ls -lha .

      - name: Upload dos artefatos do diagrama (em DOT)
        uses: actions/upload-artifact@v4
        with:
          name: diagramas-de-classes-dot
          path: |
            classes.dot
            packages.dot
          retention-days: 7