name: Gerar Diagrama de Classes

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/gerar_diagrama.yml'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Graphviz (executável)
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Instalar dependências (pylint para pyreverse, biblioteca graphviz)
        run: |
          python -m pip install --upgrade pip
          pip install pylint graphviz

      - name: Gerar diagrama de classes
        run: pyreverse -o png -p TestesClasses testes.py

      - name: Upload dos artefatos do diagrama
        uses: actions/upload-artifact@v4
        with:
          name: diagramas-de-classes
          path: |
            classes.png
            packages.png
          retention-days: 7