name: CI/CD - Geração de Artefatos com Gemini e Llama

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  generate-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Aumentado para acomodar duas gerações

    # Permissão para o workflow comitar de volta ao repositório
    permissions:
      contents: write

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      OPENROUTER_API_KEY: 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 # Nova chave para Llama

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz default-jre plantuml

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install google-generativeai openai plantuml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ========== GERAÇÃO COM GEMINI ==========
      - name: Gerar diagrama com Gemini
        run: python diagrama_gemini.py  # Script para Gemini

      - name: Renomear artefatos Gemini
        run: |
          mv diagrama_classes.puml diagrama_gemini.puml
          mv diagrama_classes.png diagrama_gemini.png

      # ========== GERAÇÃO COM LLAMA ==========
      - name: Gerar diagrama com Llama (OpenRouter)
        run: python diagrama_llama.py  # Script para Llama

      - name: Renomear artefatos Llama
        run: |
          mv diagrama_classes.puml diagrama_llama.puml
          mv diagrama_classes.png diagrama_llama.png

      # ========== ARTEFATOS E PERSISTÊNCIA ==========
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: |
            diagrama_gemini.puml
            diagrama_gemini.png
            diagrama_llama.puml
            diagrama_llama.png
          retention-days: 30

      - name: Commit e push dos diagramas gerados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main
          
          # Adiciona todos os diagramas
          git add diagrama_gemini.puml diagrama_gemini.png
          git add diagrama_llama.puml diagrama_llama.png
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-generated: Update Gemini and Llama diagrams [skip ci]"
            git push
          else
            echo "Nenhuma alteração nos diagramas. Skip commit."
          fi